### ISSUE TITLE
fedora 24 is out

### ISSUE THREAD

**Issue by maci0** [thias/retroarch-fedora#4]

**Comment by thias** [comment]
Oh, someone is using those packages! :-)

I have just now tried to quickly rebuild for Fedora 24, but it looks like gcc is now more strict by default for C++ and that EmulationStation's built fails : 

```
es-core/src/Renderer_draw_gl.cpp:90:69: error: call of overloaded 'round(float&)' is ambiguous
```

I don't have time to look into it at the moment, so contributions are welcome!

**Comment by thias** [comment]
Thanks to a patch by @ebrius (see https://github.com/Aloshi/EmulationStation/pull/594), I have now published an updated emulationstation package as well as all cores that still compile.
